import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const sampleRecipes = [
  {
    title: 'Easy Chickpea Curry',
    description: '15-minute vegan curry with canned chickpeas and spices.',
    ingredients: JSON.stringify([
      { name: 'chickpeas', qty: 1, unit: 'can' },
      { name: 'onion', qty: 1, unit: 'medium' },
      { name: 'tomato', qty: 1, unit: 'medium' },
      { name: 'garlic', qty: 2, unit: 'cloves' },
      { name: 'cumin', qty: 1, unit: 'tsp' },
      { name: 'coriander', qty: 1, unit: 'tsp' },
      { name: 'turmeric', qty: 0.5, unit: 'tsp' },
      { name: 'ginger', qty: 1, unit: 'inch' },
      { name: 'oil', qty: 1, unit: 'tbsp' },
    ]),
    steps: JSON.stringify([
      'Heat oil in a pan over medium heat.',
      'Add chopped onion, garlic, and ginger. Sauté until golden.',
      'Add spices: cumin, coriander, turmeric. Cook for 1 minute.',
      'Add chopped tomato and cook until soft.',
      'Add drained chickpeas and 1/2 cup water. Simmer for 10 minutes.',
      'Season with salt and serve hot.',
    ]),
    cuisine: 'Indian',
    tags: JSON.stringify(['vegan', 'quick', 'one-pot', 'gluten-free']),
    cookTime: 15,
    prepTime: 5,
    totalTime: 20,
    servings: 2,
    difficulty: 'easy',
    nutrition: JSON.stringify({ calories: 350, protein: 12, carbs: 55, fat: 8 }),
    mainIngredients: JSON.stringify(['chickpeas', 'onion', 'tomato', 'garlic', 'cumin']),
  },
  {
    title: 'Classic Spaghetti Carbonara',
    description: 'Traditional Italian pasta dish with eggs, cheese, and pancetta.',
    ingredients: JSON.stringify([
      { name: 'spaghetti', qty: 200, unit: 'g' },
      { name: 'pancetta', qty: 100, unit: 'g' },
      { name: 'eggs', qty: 2, unit: 'large' },
      { name: 'parmesan cheese', qty: 50, unit: 'g' },
      { name: 'black pepper', qty: 1, unit: 'tsp' },
      { name: 'salt', qty: 1, unit: 'tsp' },
    ]),
    steps: JSON.stringify([
      'Cook spaghetti in salted boiling water until al dente.',
      'In a pan, cook pancetta until crispy.',
      'Whisk eggs with grated parmesan and black pepper.',
      'Reserve pasta water, then drain spaghetti.',
      'Mix hot spaghetti with pancetta, then add egg mixture off heat.',
      'Add reserved pasta water to create creamy sauce.',
      'Serve immediately with extra parmesan.',
    ]),
    cuisine: 'Italian',
    tags: JSON.stringify(['pasta', 'quick', 'classic']),
    cookTime: 15,
    prepTime: 10,
    totalTime: 25,
    servings: 2,
    difficulty: 'medium',
    nutrition: JSON.stringify({ calories: 650, protein: 28, carbs: 70, fat: 25 }),
    mainIngredients: JSON.stringify(['spaghetti', 'pancetta', 'eggs', 'parmesan cheese']),
  },
  {
    title: 'Vegetable Stir Fry',
    description: 'Quick and healthy vegetable stir fry with tofu and soy sauce.',
    ingredients: JSON.stringify([
      { name: 'tofu', qty: 200, unit: 'g' },
      { name: 'bell peppers', qty: 2, unit: 'medium' },
      { name: 'broccoli', qty: 1, unit: 'cup' },
      { name: 'carrots', qty: 2, unit: 'medium' },
      { name: 'soy sauce', qty: 3, unit: 'tbsp' },
      { name: 'garlic', qty: 3, unit: 'cloves' },
      { name: 'ginger', qty: 1, unit: 'tsp' },
      { name: 'sesame oil', qty: 1, unit: 'tbsp' },
      { name: 'rice', qty: 1, unit: 'cup' },
    ]),
    steps: JSON.stringify([
      'Cook rice according to package instructions.',
      'Press and drain tofu, then cut into cubes.',
      'Heat sesame oil in a wok or large pan.',
      'Add tofu and cook until golden, about 5 minutes.',
      'Add garlic and ginger, cook for 30 seconds.',
      'Add vegetables and stir fry for 5-7 minutes.',
      'Add soy sauce and cook for another 2 minutes.',
      'Serve over rice.',
    ]),
    cuisine: 'Asian',
    tags: JSON.stringify(['vegetarian', 'quick', 'healthy', 'gluten-free']),
    cookTime: 20,
    prepTime: 15,
    totalTime: 35,
    servings: 2,
    difficulty: 'easy',
    nutrition: JSON.stringify({ calories: 420, protein: 20, carbs: 45, fat: 15 }),
    mainIngredients: JSON.stringify(['tofu', 'bell peppers', 'broccoli', 'carrots']),
  },
  {
    title: 'Chocolate Chip Cookies',
    description: 'Classic homemade chocolate chip cookies that are soft and chewy.',
    ingredients: JSON.stringify([
      { name: 'flour', qty: 2, unit: 'cups' },
      { name: 'butter', qty: 1, unit: 'cup' },
      { name: 'brown sugar', qty: 3/4, unit: 'cup' },
      { name: 'white sugar', qty: 3/4, unit: 'cup' },
      { name: 'eggs', qty: 2, unit: 'large' },
      { name: 'vanilla extract', qty: 1, unit: 'tsp' },
      { name: 'baking soda', qty: 1, unit: 'tsp' },
      { name: 'salt', qty: 1, unit: 'tsp' },
      { name: 'chocolate chips', qty: 2, unit: 'cups' },
    ]),
    steps: JSON.stringify([
      'Preheat oven to 375°F (190°C).',
      'Cream together butter and both sugars until fluffy.',
      'Beat in eggs and vanilla extract.',
      'In a separate bowl, whisk together flour, baking soda, and salt.',
      'Gradually mix dry ingredients into wet ingredients.',
      'Stir in chocolate chips.',
      'Drop rounded tablespoons of dough onto ungreased baking sheets.',
      'Bake for 9-11 minutes until golden brown.',
      'Cool on baking sheet for 5 minutes before transferring to wire rack.',
    ]),
    cuisine: 'American',
    tags: JSON.stringify(['dessert', 'sweet', 'baking', 'vegetarian']),
    cookTime: 12,
    prepTime: 15,
    totalTime: 27,
    servings: 24,
    difficulty: 'easy',
    nutrition: JSON.stringify({ calories: 120, protein: 2, carbs: 18, fat: 6 }),
    mainIngredients: JSON.stringify(['flour', 'butter', 'sugar', 'chocolate chips']),
  },
  {
    title: 'Greek Salad',
    description: 'Fresh and healthy Greek salad with tomatoes, cucumbers, and feta cheese.',
    ingredients: JSON.stringify([
      { name: 'tomatoes', qty: 3, unit: 'large' },
      { name: 'cucumber', qty: 1, unit: 'large' },
      { name: 'red onion', qty: 1, unit: 'small' },
      { name: 'feta cheese', qty: 100, unit: 'g' },
      { name: 'kalamata olives', qty: 1/2, unit: 'cup' },
      { name: 'olive oil', qty: 1/4, unit: 'cup' },
      { name: 'red wine vinegar', qty: 2, unit: 'tbsp' },
      { name: 'oregano', qty: 1, unit: 'tsp' },
      { name: 'salt', qty: 1, unit: 'tsp' },
      { name: 'black pepper', qty: 1/2, unit: 'tsp' },
    ]),
    steps: JSON.stringify([
      'Chop tomatoes into wedges and place in a large bowl.',
      'Dice cucumber and add to the bowl.',
      'Thinly slice red onion and add to the bowl.',
      'Add olives and crumble feta cheese over the top.',
      'In a small bowl, whisk together olive oil, vinegar, oregano, salt, and pepper.',
      'Pour dressing over salad and toss gently to combine.',
      'Let sit for 10 minutes before serving to allow flavors to meld.',
    ]),
    cuisine: 'Mediterranean',
    tags: JSON.stringify(['salad', 'healthy', 'vegetarian', 'gluten-free']),
    cookTime: 10,
    prepTime: 15,
    totalTime: 25,
    servings: 4,
    difficulty: 'easy',
    nutrition: JSON.stringify({ calories: 220, protein: 8, carbs: 12, fat: 18 }),
    mainIngredients: JSON.stringify(['tomatoes', 'cucumber', 'feta cheese', 'olives']),
  },
  {
    title: 'Beef Tacos',
    description: 'Delicious and easy beef tacos with seasoned ground beef and fresh toppings.',
    ingredients: JSON.stringify([
      { name: 'ground beef', qty: 1, unit: 'lb' },
      { name: 'taco seasoning', qty: 1, unit: 'packet' },
      { name: 'taco shells', qty: 12, unit: 'count' },
      { name: 'lettuce', qty: 1, unit: 'head' },
      { name: 'tomatoes', qty: 2, unit: 'medium' },
      { name: 'cheddar cheese', qty: 1, unit: 'cup' },
      { name: 'sour cream', qty: 1/2, unit: 'cup' },
      { name: 'onion', qty: 1, unit: 'small' },
    ]),
    steps: JSON.stringify([
      'Brown ground beef in a large skillet over medium-high heat.',
      'Drain excess fat and add taco seasoning with water as directed on packet.',
      'Simmer for 5 minutes until thickened.',
      'Warm taco shells according to package directions.',
      'Chop lettuce, dice tomatoes, and shred cheese.',
      'Finely dice onion.',
      'Fill taco shells with beef mixture.',
      'Top with lettuce, tomatoes, cheese, and sour cream.',
    ]),
    cuisine: 'Mexican',
    tags: JSON.stringify(['beef', 'quick', 'dinner', 'family-friendly']),
    cookTime: 15,
    prepTime: 20,
    totalTime: 35,
    servings: 4,
    difficulty: 'easy',
    nutrition: JSON.stringify({ calories: 450, protein: 25, carbs: 30, fat: 25 }),
    mainIngredients: JSON.stringify(['ground beef', 'taco shells', 'lettuce', 'tomatoes']),
  },
  {
    title: 'Mushroom Risotto',
    description: 'Creamy Italian rice dish with aromatic mushrooms and parmesan cheese.',
    ingredients: JSON.stringify([
      { name: 'arborio rice', qty: 1, unit: 'cup' },
      { name: 'mixed mushrooms', qty: 2, unit: 'cups' },
      { name: 'onion', qty: 1, unit: 'small' },
      { name: 'garlic', qty: 2, unit: 'cloves' },
      { name: 'vegetable broth', qty: 4, unit: 'cups' },
      { name: 'white wine', qty: 1/2, unit: 'cup' },
      { name: 'parmesan cheese', qty: 1/2, unit: 'cup' },
      { name: 'butter', qty: 2, unit: 'tbsp' },
      { name: 'olive oil', qty: 1, unit: 'tbsp' },
      { name: 'fresh thyme', qty: 1, unit: 'tsp' },
    ]),
    steps: JSON.stringify([
      'Heat olive oil and 1 tbsp butter in a large pan.',
      'Sauté chopped onion and garlic until soft.',
      'Add mushrooms and cook until golden.',
      'Add rice and toast for 2 minutes.',
      'Pour in wine and cook until absorbed.',
      'Add warm broth one ladle at a time, stirring constantly until absorbed.',
      'Continue until rice is creamy and tender, about 18-20 minutes.',
      'Stir in remaining butter and parmesan cheese.',
      'Season with salt, pepper, and fresh thyme.',
    ]),
    cuisine: 'Italian',
    tags: JSON.stringify(['vegetarian', 'comfort food', 'dinner']),
    cookTime: 25,
    prepTime: 10,
    totalTime: 35,
    servings: 4,
    difficulty: 'medium',
    nutrition: JSON.stringify({ calories: 380, protein: 12, carbs: 55, fat: 12 }),
    mainIngredients: JSON.stringify(['arborio rice', 'mushrooms', 'parmesan cheese']),
  },
  {
    title: 'Honey Glazed Salmon',
    description: 'Perfectly cooked salmon with a sweet and savory honey glaze.',
    ingredients: JSON.stringify([
      { name: 'salmon fillets', qty: 4, unit: '6 oz each' },
      { name: 'honey', qty: 3, unit: 'tbsp' },
      { name: 'soy sauce', qty: 2, unit: 'tbsp' },
      { name: 'lemon juice', qty: 1, unit: 'tbsp' },
      { name: 'garlic', qty: 2, unit: 'cloves' },
      { name: 'olive oil', qty: 1, unit: 'tbsp' },
      { name: 'fresh dill', qty: 1, unit: 'tbsp' },
      { name: 'salt', qty: 1, unit: 'tsp' },
      { name: 'black pepper', qty: 1/2, unit: 'tsp' },
    ]),
    steps: JSON.stringify([
      'Preheat oven to 400°F (200°C).',
      'Pat salmon dry and season with salt and pepper.',
      'Heat olive oil in an oven-safe skillet over medium-high heat.',
      'Sear salmon skin-side up for 4 minutes until golden.',
      'Flip and cook for 2 more minutes.',
      'Whisk together honey, soy sauce, lemon juice, and minced garlic.',
      'Pour glaze over salmon and transfer to oven.',
      'Roast for 5-7 minutes until salmon flakes easily.',
      'Garnish with fresh dill and serve.',
    ]),
    cuisine: 'American',
    tags: JSON.stringify(['seafood', 'healthy', 'dinner', 'gluten-free']),
    cookTime: 15,
    prepTime: 10,
    totalTime: 25,
    servings: 4,
    difficulty: 'easy',
    nutrition: JSON.stringify({ calories: 320, protein: 35, carbs: 12, fat: 18 }),
    mainIngredients: JSON.stringify(['salmon', 'honey', 'soy sauce']),
  },
  {
    title: 'Vegetable Lasagna',
    description: 'Layered pasta with roasted vegetables and creamy ricotta filling.',
    ingredients: JSON.stringify([
      { name: 'lasagna noodles', qty: 12, unit: 'pieces' },
      { name: 'zucchini', qty: 2, unit: 'medium' },
      { name: 'eggplant', qty: 1, unit: 'medium' },
      { name: 'bell peppers', qty: 2, unit: 'medium' },
      { name: 'ricotta cheese', qty: 2, unit: 'cups' },
      { name: 'mozzarella cheese', qty: 2, unit: 'cups' },
      { name: 'parmesan cheese', qty: 1, unit: 'cup' },
      { name: 'marinara sauce', qty: 3, unit: 'cups' },
      { name: 'spinach', qty: 2, unit: 'cups' },
      { name: 'egg', qty: 1, unit: 'large' },
    ]),
    steps: JSON.stringify([
      'Preheat oven to 375°F (190°C).',
      'Roast diced zucchini, eggplant, and bell peppers at 425°F for 20 minutes.',
      'Cook lasagna noodles according to package directions.',
      'Mix ricotta with egg and half the parmesan cheese.',
      'Spread 1/2 cup sauce in the bottom of a 9x13 pan.',
      'Layer noodles, ricotta mixture, roasted vegetables, and spinach.',
      'Top with more sauce and mozzarella cheese.',
      'Repeat layers, ending with sauce and remaining cheeses.',
      'Cover with foil and bake 30 minutes.',
      'Remove foil and bake 15 more minutes until bubbly and golden.',
    ]),
    cuisine: 'Italian',
    tags: JSON.stringify(['vegetarian', 'pasta', 'baked', 'comfort food']),
    cookTime: 45,
    prepTime: 30,
    totalTime: 75,
    servings: 8,
    difficulty: 'medium',
    nutrition: JSON.stringify({ calories: 350, protein: 20, carbs: 35, fat: 15 }),
    mainIngredients: JSON.stringify(['lasagna noodles', 'vegetables', 'ricotta cheese']),
  },
  {
    title: 'Chicken Tikka Masala',
    description: 'Tender chicken in a rich, creamy tomato-based Indian curry sauce.',
    ingredients: JSON.stringify([
      { name: 'chicken thighs', qty: 2, unit: 'lbs' },
      { name: 'yogurt', qty: 1, unit: 'cup' },
      { name: 'tomato sauce', qty: 2, unit: 'cups' },
      { name: 'heavy cream', qty: 1, unit: 'cup' },
      { name: 'onion', qty: 1, unit: 'large' },
      { name: 'garlic', qty: 4, unit: 'cloves' },
      { name: 'ginger', qty: 1, unit: 'inch' },
      { name: 'garam masala', qty: 2, unit: 'tbsp' },
      { name: 'cumin', qty: 1, unit: 'tsp' },
      { name: 'turmeric', qty: 1, unit: 'tsp' },
    ]),
    steps: JSON.stringify([
      'Cut chicken into bite-sized pieces.',
      'Marinate in yogurt and half the spices for 1 hour.',
      'Sauté chopped onion, garlic, and ginger until golden.',
      'Add remaining spices and cook for 1 minute.',
      'Add tomato sauce and simmer for 10 minutes.',
      'Add marinated chicken and cook until tender, about 15 minutes.',
      'Stir in heavy cream and simmer for 5 minutes.',
      'Garnish with fresh cilantro and serve over rice.',
    ]),
    cuisine: 'Indian',
    tags: JSON.stringify(['chicken', 'curry', 'dinner']),
    cookTime: 30,
    prepTime: 20,
    totalTime: 50,
    servings: 6,
    difficulty: 'medium',
    nutrition: JSON.stringify({ calories: 420, protein: 30, carbs: 15, fat: 28 }),
    mainIngredients: JSON.stringify(['chicken', 'tomato sauce', 'cream']),
  },
  {
    title: 'Quinoa Buddha Bowl',
    description: 'Nutritious grain bowl with quinoa, roasted vegetables, and tahini dressing.',
    ingredients: JSON.stringify([
      { name: 'quinoa', qty: 1, unit: 'cup' },
      { name: 'sweet potato', qty: 1, unit: 'large' },
      { name: 'broccoli', qty: 2, unit: 'cups' },
      { name: 'chickpeas', qty: 1, unit: 'can' },
      { name: 'avocado', qty: 1, unit: 'medium' },
      { name: 'tahini', qty: 1/4, unit: 'cup' },
      { name: 'lemon juice', qty: 2, unit: 'tbsp' },
      { name: 'olive oil', qty: 2, unit: 'tbsp' },
      { name: 'pumpkin seeds', qty: 2, unit: 'tbsp' },
    ]),
    steps: JSON.stringify([
      'Preheat oven to 400°F (200°C).',
      'Cook quinoa according to package directions.',
      'Dice sweet potato and toss with olive oil, salt, and pepper.',
      'Roast sweet potato for 25 minutes until tender.',
      'Toss broccoli with olive oil and roast for 15 minutes.',
      'Drain and rinse chickpeas, then roast for 10 minutes.',
      'Whisk together tahini, lemon juice, and 2 tbsp water for dressing.',
      'Assemble bowls with quinoa, roasted vegetables, and chickpeas.',
      'Top with sliced avocado and pumpkin seeds.',
      'Drizzle with tahini dressing and serve.',
    ]),
    cuisine: 'Mediterranean',
    tags: JSON.stringify(['vegetarian', 'healthy', 'gluten-free', 'grain bowl']),
    cookTime: 30,
    prepTime: 15,
    totalTime: 45,
    servings: 4,
    difficulty: 'easy',
    nutrition: JSON.stringify({ calories: 450, protein: 15, carbs: 50, fat: 20 }),
    mainIngredients: JSON.stringify(['quinoa', 'sweet potato', 'broccoli', 'chickpeas']),
  },
  {
    title: 'Beef Bourguignon',
    description: 'Classic French stew with tender beef, mushrooms, and pearl onions in red wine sauce.',
    ingredients: JSON.stringify([
      { name: 'beef chuck', qty: 3, unit: 'lbs' },
      { name: 'red wine', qty: 3, unit: 'cups' },
      { name: 'beef broth', qty: 2, unit: 'cups' },
      { name: 'bacon', qty: 4, unit: 'slices' },
      { name: 'pearl onions', qty: 1, unit: 'cup' },
      { name: 'mushrooms', qty: 1, unit: 'lb' },
      { name: 'carrots', qty: 3, unit: 'medium' },
      { name: 'garlic', qty: 3, unit: 'cloves' },
      { name: 'tomato paste', qty: 2, unit: 'tbsp' },
    ]),
    steps: JSON.stringify([
      'Cut beef into 2-inch cubes and season with salt and pepper.',
      'Cook bacon in a Dutch oven until crispy, remove and set aside.',
      'Brown beef in bacon fat in batches, remove and set aside.',
      'Sauté onions, mushrooms, and carrots until golden.',
      'Add garlic and tomato paste, cook for 1 minute.',
      'Return beef and bacon to pot.',
      'Add wine and broth, bring to a boil.',
      'Cover and simmer in oven at 325°F for 2.5-3 hours.',
      'Skim fat and adjust seasoning before serving with mashed potatoes.',
    ]),
    cuisine: 'French',
    tags: JSON.stringify(['beef', 'stew', 'dinner', 'comfort food']),
    cookTime: 180,
    prepTime: 30,
    totalTime: 210,
    servings: 6,
    difficulty: 'hard',
    nutrition: JSON.stringify({ calories: 520, protein: 35, carbs: 20, fat: 32 }),
    mainIngredients: JSON.stringify(['beef', 'red wine', 'mushrooms']),
  },
  {
    title: 'Shrimp Scampi',
    description: 'Garlic butter shrimp with white wine sauce served over linguine.',
    ingredients: JSON.stringify([
      { name: 'shrimp', qty: 1, unit: 'lb' },
      { name: 'linguine', qty: 1, unit: 'lb' },
      { name: 'butter', qty: 4, unit: 'tbsp' },
      { name: 'olive oil', qty: 2, unit: 'tbsp' },
      { name: 'garlic', qty: 6, unit: 'cloves' },
      { name: 'white wine', qty: 1/2, unit: 'cup' },
      { name: 'lemon juice', qty: 2, unit: 'tbsp' },
      { name: 'parsley', qty: 1/4, unit: 'cup' },
      { name: 'red pepper flakes', qty: 1/4, unit: 'tsp' },
    ]),
    steps: JSON.stringify([
      'Cook linguine according to package directions.',
      'Peel and devein shrimp, leaving tails on if desired.',
      'Heat olive oil and 2 tbsp butter in a large skillet.',
      'Add minced garlic and red pepper flakes, cook for 30 seconds.',
      'Add shrimp and cook until pink, about 2-3 minutes per side.',
      'Add wine and lemon juice, simmer for 2 minutes.',
      'Stir in remaining butter until melted.',
      'Toss with cooked linguine and chopped parsley.',
      'Serve immediately with extra lemon wedges.',
    ]),
    cuisine: 'Italian',
    tags: JSON.stringify(['seafood', 'pasta', 'quick', 'dinner']),
    cookTime: 15,
    prepTime: 15,
    totalTime: 30,
    servings: 4,
    difficulty: 'easy',
    nutrition: JSON.stringify({ calories: 480, protein: 25, carbs: 55, fat: 18 }),
    mainIngredients: JSON.stringify(['shrimp', 'garlic', 'butter']),
  },
  {
    title: 'Pumpkin Soup',
    description: 'Creamy autumn soup with roasted pumpkin, warming spices, and coconut milk.',
    ingredients: JSON.stringify([
      { name: 'pumpkin', qty: 3, unit: 'lbs' },
      { name: 'onion', qty: 1, unit: 'large' },
      { name: 'garlic', qty: 3, unit: 'cloves' },
      { name: 'ginger', qty: 1, unit: 'inch' },
      { name: 'coconut milk', qty: 1, unit: 'can' },
      { name: 'vegetable broth', qty: 4, unit: 'cups' },
      { name: 'curry powder', qty: 1, unit: 'tbsp' },
      { name: 'nutmeg', qty: 1/2, unit: 'tsp' },
      { name: 'olive oil', qty: 2, unit: 'tbsp' },
    ]),
    steps: JSON.stringify([
      'Preheat oven to 400°F (200°C).',
      'Cut pumpkin in half, remove seeds, and roast cut-side down for 45 minutes.',
      'Sauté chopped onion, garlic, and ginger in olive oil until soft.',
      'Add curry powder and nutmeg, cook for 1 minute.',
      'Scoop pumpkin flesh from skin and add to pot.',
      'Add vegetable broth and simmer for 20 minutes.',
      'Blend until smooth with an immersion blender.',
      'Stir in coconut milk and season with salt and pepper.',
      'Serve hot with crusty bread and a drizzle of cream.',
    ]),
    cuisine: 'American',
    tags: JSON.stringify(['soup', 'vegetarian', 'fall', 'gluten-free']),
    cookTime: 30,
    prepTime: 20,
    totalTime: 50,
    servings: 6,
    difficulty: 'easy',
    nutrition: JSON.stringify({ calories: 220, protein: 5, carbs: 25, fat: 12 }),
    mainIngredients: JSON.stringify(['pumpkin', 'coconut milk', 'curry powder']),
  },
  {
    title: 'Beef and Broccoli Stir Fry',
    description: 'Chinese takeout favorite with tender beef and crisp broccoli in savory sauce.',
    ingredients: JSON.stringify([
      { name: 'flank steak', qty: 1, unit: 'lb' },
      { name: 'broccoli', qty: 1, unit: 'lb' },
      { name: 'soy sauce', qty: 1/4, unit: 'cup' },
      { name: 'brown sugar', qty: 2, unit: 'tbsp' },
      { name: 'rice vinegar', qty: 1, unit: 'tbsp' },
      { name: 'sesame oil', qty: 1, unit: 'tsp' },
      { name: 'cornstarch', qty: 1, unit: 'tbsp' },
      { name: 'garlic', qty: 3, unit: 'cloves' },
      { name: 'ginger', qty: 1, unit: 'tsp' },
    ]),
    steps: JSON.stringify([
      'Slice beef against the grain into thin strips.',
      'Marinate beef in 2 tbsp soy sauce for 15 minutes.',
      'Cut broccoli into florets and blanch in boiling water for 2 minutes.',
      'Mix remaining soy sauce, brown sugar, vinegar, and cornstarch for sauce.',
      'Heat oil in a wok over high heat.',
      'Stir-fry beef until browned, about 3 minutes, remove and set aside.',
      'Add garlic and ginger, cook for 30 seconds.',
      'Add broccoli and stir-fry for 2 minutes.',
      'Return beef to wok, add sauce and cook until thickened.',
    ]),
    cuisine: 'Chinese',
    tags: JSON.stringify(['beef', 'quick', 'dinner', 'stir fry']),
    cookTime: 20,
    prepTime: 20,
    totalTime: 40,
    servings: 4,
    difficulty: 'medium',
    nutrition: JSON.stringify({ calories: 320, protein: 28, carbs: 20, fat: 16 }),
    mainIngredients: JSON.stringify(['beef', 'broccoli', 'soy sauce']),
  },
  {
    title: 'Caprese Stuffed Garlic Bread',
    description: 'Warm garlic bread stuffed with fresh mozzarella, tomatoes, and basil.',
    ingredients: JSON.stringify([
      { name: 'baguette', qty: 1, unit: '12 inch' },
      { name: 'mozzarella cheese', qty: 8, unit: 'oz' },
      { name: 'tomatoes', qty: 2, unit: 'medium' },
      { name: 'fresh basil', qty: 1/2, unit: 'cup' },
      { name: 'garlic', qty: 4, unit: 'cloves' },
      { name: 'butter', qty: 1/2, unit: 'cup' },
      { name: 'olive oil', qty: 2, unit: 'tbsp' },
      { name: 'balsamic vinegar', qty: 1, unit: 'tbsp' },
      { name: 'salt', qty: 1, unit: 'tsp' },
    ]),
    steps: JSON.stringify([
      'Preheat oven to 400°F (200°C).',
      'Slice baguette in half lengthwise, hollow out some bread.',
      'Mince garlic and mix with softened butter.',
      'Spread garlic butter on both cut sides of bread.',
      'Layer sliced mozzarella, tomatoes, and basil in bottom half.',
      'Drizzle with olive oil and balsamic vinegar.',
      'Season with salt and pepper.',
      'Place top on sandwich and wrap in foil.',
      'Bake for 15 minutes until cheese is melted and bread is crispy.',
    ]),
    cuisine: 'Italian',
    tags: JSON.stringify(['appetizer', 'vegetarian', 'comfort food', 'quick']),
    cookTime: 15,
    prepTime: 15,
    totalTime: 30,
    servings: 4,
    difficulty: 'easy',
    nutrition: JSON.stringify({ calories: 380, protein: 15, carbs: 35, fat: 20 }),
    mainIngredients: JSON.stringify(['bread', 'mozzarella', 'tomatoes', 'basil']),
  },
  {
    title: 'Chicken Biryani',
    description: 'Fragrant rice dish with tender chicken and aromatic spices.',
    ingredients: JSON.stringify([
      { name: 'basmati rice', qty: 2, unit: 'cups' },
      { name: 'chicken', qty: 1, unit: 'lb' },
      { name: 'yogurt', qty: 1/2, unit: 'cup' },
      { name: 'onion', qty: 2, unit: 'large' },
      { name: 'tomatoes', qty: 2, unit: 'medium' },
      { name: 'ginger-garlic paste', qty: 1, unit: 'tbsp' },
      { name: 'biryani masala', qty: 2, unit: 'tbsp' },
      { name: 'saffron', qty: 1/2, unit: 'tsp' },
      { name: 'mint leaves', qty: 1/4, unit: 'cup' },
      { name: 'cilantro', qty: 1/4, unit: 'cup' },
    ]),
    steps: JSON.stringify([
      'Marinate chicken with yogurt and half the spices for 1 hour.',
      'Soak saffron in warm milk for 10 minutes.',
      'Fry sliced onions until golden brown, set aside half for garnish.',
      'Cook marinated chicken with tomatoes until tender.',
      'Parboil rice with whole spices until 80% cooked.',
      'Layer rice and chicken in a heavy-bottomed pot.',
      'Sprinkle fried onions, mint, and cilantro between layers.',
      'Cover and cook on low heat for 20 minutes (dum cooking).',
      'Mix in saffron milk and serve hot with raita.',
    ]),
    cuisine: 'Indian',
    tags: JSON.stringify(['chicken', 'rice', 'dinner', 'special occasion']),
    cookTime: 40,
    prepTime: 30,
    totalTime: 70,
    servings: 4,
    difficulty: 'medium',
    nutrition: JSON.stringify({ calories: 520, protein: 25, carbs: 65, fat: 15 }),
    mainIngredients: JSON.stringify(['chicken', 'basmati rice', 'biryani masala']),
  },
  {
    title: 'Palak Paneer',
    description: 'Creamy spinach curry with cubes of Indian cottage cheese.',
    ingredients: JSON.stringify([
      { name: 'paneer', qty: 200, unit: 'g' },
      { name: 'spinach', qty: 500, unit: 'g' },
      { name: 'onion', qty: 1, unit: 'large' },
      { name: 'garlic', qty: 4, unit: 'cloves' },
      { name: 'ginger', qty: 1, unit: 'inch' },
      { name: 'tomatoes', qty: 2, unit: 'medium' },
      { name: 'cream', qty: 1/4, unit: 'cup' },
      { name: 'garam masala', qty: 1, unit: 'tsp' },
      { name: 'cumin', qty: 1, unit: 'tsp' },
      { name: 'turmeric', qty: 1/2, unit: 'tsp' },
    ]),
    steps: JSON.stringify([
      'Blanch spinach in boiling water for 2 minutes, drain and blend to paste.',
      'Cut paneer into cubes and shallow fry until golden.',
      'Sauté onions, garlic, and ginger until golden.',
      'Add tomatoes and cook until soft and pulpy.',
      'Add spices and cook for 1 minute.',
      'Add spinach paste and 1/2 cup water, simmer for 10 minutes.',
      'Stir in cream and cooked paneer.',
      'Simmer for 5 minutes and adjust seasoning.',
      'Serve hot with roti or naan.',
    ]),
    cuisine: 'Indian',
    tags: JSON.stringify(['vegetarian', 'curry', 'dinner', 'gluten-free']),
    cookTime: 30,
    prepTime: 20,
    totalTime: 50,
    servings: 4,
    difficulty: 'medium',
    nutrition: JSON.stringify({ calories: 320, protein: 18, carbs: 15, fat: 22 }),
    mainIngredients: JSON.stringify(['paneer', 'spinach', 'cream']),
  },
  {
    title: 'Aloo Gobi',
    description: 'Dry curry with potatoes and cauliflower flavored with aromatic spices.',
    ingredients: JSON.stringify([
      { name: 'potatoes', qty: 2, unit: 'medium' },
      { name: 'cauliflower', qty: 1/2, unit: 'head' },
      { name: 'onion', qty: 1, unit: 'large' },
      { name: 'tomatoes', qty: 2, unit: 'medium' },
      { name: 'ginger-garlic paste', qty: 1, unit: 'tbsp' },
      { name: 'cumin', qty: 1, unit: 'tsp' },
      { name: 'coriander powder', qty: 1, unit: 'tsp' },
      { name: 'turmeric', qty: 1/2, unit: 'tsp' },
      { name: 'garam masala', qty: 1/2, unit: 'tsp' },
      { name: 'cilantro', qty: 2, unit: 'tbsp' },
    ]),
    steps: JSON.stringify([
      'Cut potatoes and cauliflower into bite-sized pieces.',
      'Heat oil in a pan and add cumin seeds.',
      'Add onions and cook until golden brown.',
      'Add ginger-garlic paste and cook for 1 minute.',
      'Add tomatoes and cook until soft and pulpy.',
      'Add all spices and cook for 1 minute.',
      'Add potatoes and 1/4 cup water, cover and cook for 10 minutes.',
      'Add cauliflower and cook for another 10 minutes.',
      'Garnish with fresh cilantro and serve hot.',
    ]),
    cuisine: 'Indian',
    tags: JSON.stringify(['vegetarian', 'curry', 'quick', 'gluten-free']),
    cookTime: 25,
    prepTime: 15,
    totalTime: 40,
    servings: 4,
    difficulty: 'easy',
    nutrition: JSON.stringify({ calories: 180, protein: 5, carbs: 30, fat: 6 }),
    mainIngredients: JSON.stringify(['potatoes', 'cauliflower', 'cumin']),
  },
  {
    title: 'Dal Tadka',
    description: 'Yellow lentil curry tempered with aromatic spices and herbs.',
    ingredients: JSON.stringify([
      { name: 'toor dal', qty: 1, unit: 'cup' },
      { name: 'onion', qty: 1, unit: 'large' },
      { name: 'tomatoes', qty: 2, unit: 'medium' },
      { name: 'ginger-garlic paste', qty: 1, unit: 'tsp' },
      { name: 'cumin', qty: 1, unit: 'tsp' },
      { name: 'mustard seeds', qty: 1/2, unit: 'tsp' },
      { name: 'turmeric', qty: 1/2, unit: 'tsp' },
      { name: 'red chili powder', qty: 1, unit: 'tsp' },
      { name: 'garam masala', qty: 1/2, unit: 'tsp' },
      { name: 'cilantro', qty: 2, unit: 'tbsp' },
    ]),
    steps: JSON.stringify([
      'Wash and pressure cook dal with turmeric and salt for 3 whistles.',
      'Mash cooked dal and set aside.',
      'Heat ghee in a pan and add cumin and mustard seeds.',
      'Add chopped onions and cook until golden.',
      'Add ginger-garlic paste and cook for 1 minute.',
      'Add tomatoes and cook until soft.',
      'Add red chili powder and garam masala, cook for 1 minute.',
      'Add mashed dal and 1/2 cup water, simmer for 10 minutes.',
      'Garnish with fresh cilantro and serve with rice.',
    ]),
    cuisine: 'Indian',
    tags: JSON.stringify(['vegetarian', 'lentils', 'comfort food', 'gluten-free']),
    cookTime: 30,
    prepTime: 10,
    totalTime: 40,
    servings: 4,
    difficulty: 'easy',
    nutrition: JSON.stringify({ calories: 220, protein: 12, carbs: 35, fat: 4 }),
    mainIngredients: JSON.stringify(['toor dal', 'onion', 'cumin']),
  },
  {
    title: 'Butter Chicken',
    description: 'Rich and creamy tomato-based curry with tender chicken pieces.',
    ingredients: JSON.stringify([
      { name: 'chicken', qty: 1, unit: 'lb' },
      { name: 'butter', qty: 3, unit: 'tbsp' },
      { name: 'onion', qty: 1, unit: 'large' },
      { name: 'garlic', qty: 4, unit: 'cloves' },
      { name: 'ginger', qty: 1, unit: 'inch' },
      { name: 'tomato puree', qty: 1, unit: 'cup' },
      { name: 'heavy cream', qty: 1/2, unit: 'cup' },
      { name: 'garam masala', qty: 1, unit: 'tsp' },
      { name: 'kasuri methi', qty: 1/2, unit: 'tsp' },
      { name: 'cashews', qty: 10, unit: 'pieces' },
    ]),
    steps: JSON.stringify([
      'Cut chicken into pieces and cook in a pressure cooker with water until tender.',
      'Blend cashews with 1/4 cup water to make a paste.',
      'Heat butter in a pan and sauté onions until golden.',
      'Add ginger-garlic paste and cook for 1 minute.',
      'Add tomato puree and cook until oil separates.',
      'Add garam masala and cashew paste, cook for 2 minutes.',
      'Add cooked chicken and 1/2 cup water, simmer for 10 minutes.',
      'Stir in cream and kasuri methi, simmer for 5 minutes.',
      'Serve hot with naan or rice.',
    ]),
    cuisine: 'Indian',
    tags: JSON.stringify(['chicken', 'curry', 'dinner', 'comfort food']),
    cookTime: 40,
    prepTime: 20,
    totalTime: 60,
    servings: 4,
    difficulty: 'medium',
    nutrition: JSON.stringify({ calories: 450, protein: 30, carbs: 15, fat: 32 }),
    mainIngredients: JSON.stringify(['chicken', 'butter', 'tomato puree']),
  },
  {
    title: 'Chana Masala',
    description: 'Spicy chickpea curry cooked with onions, tomatoes, and traditional spices.',
    ingredients: JSON.stringify([
      { name: 'chickpeas', qty: 2, unit: 'cups' },
      { name: 'onion', qty: 1, unit: 'large' },
      { name: 'tomatoes', qty: 3, unit: 'medium' },
      { name: 'ginger-garlic paste', qty: 1, unit: 'tbsp' },
      { name: 'cumin', qty: 1, unit: 'tsp' },
      { name: 'coriander powder', qty: 1, unit: 'tsp' },
      { name: 'amchur', qty: 1, unit: 'tsp' },
      { name: 'garam masala', qty: 1/2, unit: 'tsp' },
      { name: 'red chili powder', qty: 1, unit: 'tsp' },
      { name: 'cilantro', qty: 2, unit: 'tbsp' },
    ]),
    steps: JSON.stringify([
      'Soak chickpeas overnight and pressure cook until tender.',
      'Heat oil in a pan and add cumin seeds.',
      'Add chopped onions and cook until golden brown.',
      'Add ginger-garlic paste and cook for 1 minute.',
      'Add chopped tomatoes and cook until soft and pulpy.',
      'Add all spices and cook for 1 minute.',
      'Add cooked chickpeas and 1/2 cup water, simmer for 15 minutes.',
      'Add amchur and cook for 2 minutes.',
      'Garnish with fresh cilantro and serve with rice.',
    ]),
    cuisine: 'Indian',
    tags: JSON.stringify(['vegan', 'curry', 'quick', 'gluten-free']),
    cookTime: 30,
    prepTime: 15,
    totalTime: 45,
    servings: 4,
    difficulty: 'easy',
    nutrition: JSON.stringify({ calories: 280, protein: 12, carbs: 45, fat: 6 }),
    mainIngredients: JSON.stringify(['chickpeas', 'onion', 'tomatoes']),
  },
  {
    title: 'Vegetable Korma',
    description: 'Creamy and mild curry with mixed vegetables in rich coconut sauce.',
    ingredients: JSON.stringify([
      { name: 'mixed vegetables', qty: 4, unit: 'cups' },
      { name: 'coconut milk', qty: 1, unit: 'can' },
      { name: 'onion', qty: 1, unit: 'large' },
      { name: 'garlic', qty: 3, unit: 'cloves' },
      { name: 'ginger', qty: 1, unit: 'inch' },
      { name: 'cashew nuts', qty: 10, unit: 'pieces' },
      { name: 'garam masala', qty: 1, unit: 'tsp' },
      { name: 'cumin', qty: 1/2, unit: 'tsp' },
      { name: 'coriander powder', qty: 1, unit: 'tsp' },
      { name: 'cilantro', qty: 2, unit: 'tbsp' },
    ]),
    steps: JSON.stringify([
      'Cut vegetables into bite-sized pieces and blanch in salted water.',
      'Blend cashew nuts with 1/4 cup water to make a paste.',
      'Heat oil in a pan and sauté onions until golden.',
      'Add ginger-garlic paste and cook for 1 minute.',
      'Add all spices and cook for 1 minute.',
      'Add cashew paste and cook for 2 minutes.',
      'Add coconut milk and bring to a gentle boil.',
      'Add blanched vegetables and simmer for 10 minutes.',
      'Garnish with fresh cilantro and serve with naan.',
    ]),
    cuisine: 'Indian',
    tags: JSON.stringify(['vegetarian', 'curry', 'comfort food', 'gluten-free']),
    cookTime: 30,
    prepTime: 20,
    totalTime: 50,
    servings: 4,
    difficulty: 'medium',
    nutrition: JSON.stringify({ calories: 250, protein: 8, carbs: 25, fat: 14 }),
    mainIngredients: JSON.stringify(['mixed vegetables', 'coconut milk', 'cashew nuts']),
  },
  {
    title: 'Samosa',
    description: 'Crispy pastry filled with spiced potatoes and peas, perfect as a snack.',
    ingredients: JSON.stringify([
      { name: 'potatoes', qty: 3, unit: 'medium' },
      { name: 'green peas', qty: 1/2, unit: 'cup' },
      { name: 'onion', qty: 1, unit: 'large' },
      { name: 'ginger-garlic paste', qty: 1, unit: 'tsp' },
      { name: 'cumin', qty: 1, unit: 'tsp' },
      { name: 'coriander powder', qty: 1, unit: 'tsp' },
      { name: 'garam masala', qty: 1/2, unit: 'tsp' },
      { name: 'samosa wrappers', qty: 10, unit: 'pieces' },
      { name: 'oil', qty: 2, unit: 'tbsp' },
      { name: 'cilantro', qty: 2, unit: 'tbsp' },
    ]),
    steps: JSON.stringify([
      'Boil and dice potatoes, set aside.',
      'Heat oil in a pan and add cumin seeds.',
      'Add chopped onions and cook until golden.',
      'Add ginger-garlic paste and cook for 1 minute.',
      'Add green peas and all spices, cook for 2 minutes.',
      'Add diced potatoes and mix well, cook for 5 minutes.',
      'Cool the filling completely.',
      'Fill samosa wrappers with potato mixture and seal edges.',
      'Deep fry until golden brown and crispy.',
    ]),
    cuisine: 'Indian',
    tags: JSON.stringify(['vegetarian', 'snack', 'appetizer', 'gluten-free']),
    cookTime: 20,
    prepTime: 30,
    totalTime: 50,
    servings: 4,
    difficulty: 'medium',
    nutrition: JSON.stringify({ calories: 280, protein: 6, carbs: 35, fat: 12 }),
    mainIngredients: JSON.stringify(['potatoes', 'green peas', 'samosa wrappers']),
  },
  {
    title: 'Rogan Josh',
    description: 'Aromatic lamb curry from Kashmir with rich gravy and tender meat.',
    ingredients: JSON.stringify([
      { name: 'lamb', qty: 1, unit: 'lb' },
      { name: 'onion', qty: 2, unit: 'large' },
      { name: 'garlic', qty: 5, unit: 'cloves' },
      { name: 'ginger', qty: 2, unit: 'inch' },
      { name: 'yogurt', qty: 1/2, unit: 'cup' },
      { name: 'tomato puree', qty: 1/2, unit: 'cup' },
      { name: 'kashmiri red chili powder', qty: 1, unit: 'tbsp' },
      { name: 'garam masala', qty: 1, unit: 'tsp' },
      { name: 'cinnamon', qty: 1, unit: 'stick' },
      { name: 'cilantro', qty: 2, unit: 'tbsp' },
    ]),
    steps: JSON.stringify([
      'Cut lamb into pieces and marinate with yogurt and half the spices for 1 hour.',
      'Heat oil in a pan and brown lamb pieces on all sides, remove and set aside.',
      'In the same pan, sauté sliced onions until golden brown.',
      'Add ginger-garlic paste and cook until golden.',
      'Add tomato puree and cook until oil separates.',
      'Add remaining spices and 1 cup water, bring to a boil.',
      'Add lamb and simmer covered for 45 minutes until tender.',
      'Adjust consistency and garnish with fresh cilantro.',
      'Serve hot with rice or naan.',
    ]),
    cuisine: 'Indian',
    tags: JSON.stringify(['lamb', 'curry', 'dinner', 'special occasion']),
    cookTime: 60,
    prepTime: 30,
    totalTime: 90,
    servings: 4,
    difficulty: 'medium',
    nutrition: JSON.stringify({ calories: 420, protein: 35, carbs: 10, fat: 28 }),
    mainIngredients: JSON.stringify(['lamb', 'onion', 'kashmiri red chili powder']),
  },
  {
    title: 'Dosa',
    description: 'Crispy South Indian crepe made from fermented rice and lentil batter.',
    ingredients: JSON.stringify([
      { name: 'rice', qty: 1, unit: 'cup' },
      { name: 'urad dal', qty: 1/4, unit: 'cup' },
      { name: 'fenugreek seeds', qty: 1/2, unit: 'tsp' },
      { name: 'potatoes', qty: 2, unit: 'medium' },
      { name: 'onion', qty: 1, unit: 'large' },
      { name: 'green chilies', qty: 2, unit: 'pieces' },
      { name: 'mustard seeds', qty: 1/2, unit: 'tsp' },
      { name: 'curry leaves', qty: 10, unit: 'leaves' },
      { name: 'oil', qty: 2, unit: 'tbsp' },
      { name: 'coconut chutney', qty: 1/2, unit: 'cup' },
    ]),
    steps: JSON.stringify([
      'Soak rice, urad dal, and fenugreek seeds separately for 4 hours.',
      'Grind to make separate batters and mix together.',
      'Ferment overnight until doubled in volume.',
      'Boil and mash potatoes, set aside.',
      'Heat oil in a pan and add mustard seeds.',
      'Add chopped onions, green chilies, and curry leaves.',
      'Add mashed potatoes and spices, mix well.',
      'Heat a non-stick pan and pour dosa batter in circular motion.',
      'Cook until crispy and serve with potato filling and chutney.',
    ]),
    cuisine: 'Indian',
    tags: JSON.stringify(['vegetarian', 'breakfast', 'gluten-free', 'south indian']),
    cookTime: 20,
    prepTime: 20,
    totalTime: 320,
    servings: 4,
    difficulty: 'hard',
    nutrition: JSON.stringify({ calories: 180, protein: 6, carbs: 32, fat: 3 }),
    mainIngredients: JSON.stringify(['rice', 'urad dal', 'potatoes']),
  },
  {
    title: 'Pani Puri',
    description: 'Popular street food with crispy hollow puris filled with spicy water and chickpeas.',
    ingredients: JSON.stringify([
      { name: 'semolina', qty: 1, unit: 'cup' },
      { name: 'chickpeas', qty: 1/2, unit: 'cup' },
      { name: 'potatoes', qty: 2, unit: 'medium' },
      { name: 'mint leaves', qty: 1/2, unit: 'cup' },
      { name: 'coriander leaves', qty: 1/2, unit: 'cup' },
      { name: 'green chilies', qty: 3, unit: 'pieces' },
      { name: 'tamarind', qty: 2, unit: 'tbsp' },
      { name: 'chaat masala', qty: 1, unit: 'tsp' },
      { name: 'black salt', qty: 1/2, unit: 'tsp' },
      { name: 'oil', qty: 2, unit: 'tbsp' },
    ]),
    steps: JSON.stringify([
      'Make dough with semolina and water, rest for 30 minutes.',
      'Roll into small balls and flatten into thin circles.',
      'Deep fry until crispy and golden, cool completely.',
      'Boil and dice potatoes, set aside.',
      'For mint water, blend mint, coriander, green chilies with water and strain.',
      'For tamarind water, soak tamarind and extract juice.',
      'Add chaat masala and black salt to both waters.',
      'Fill puris with chickpeas, potatoes and both waters.',
      'Serve immediately as a refreshing snack.',
    ]),
    cuisine: 'Indian',
    tags: JSON.stringify(['vegetarian', 'snack', 'street food', 'gluten-free']),
    cookTime: 30,
    prepTime: 40,
    totalTime: 70,
    servings: 4,
    difficulty: 'hard',
    nutrition: JSON.stringify({ calories: 220, protein: 6, carbs: 35, fat: 6 }),
    mainIngredients: JSON.stringify(['semolina', 'chickpeas', 'mint leaves']),
  },
  {
    title: 'Malai Kofta',
    description: 'Deep-fried vegetable balls in rich, creamy tomato-based gravy.',
    ingredients: JSON.stringify([
      { name: 'potatoes', qty: 3, unit: 'medium' },
      { name: 'paneer', qty: 100, unit: 'g' },
      { name: 'carrots', qty: 2, unit: 'medium' },
      { name: 'onion', qty: 2, unit: 'large' },
      { name: 'cashews', qty: 15, unit: 'pieces' },
      { name: 'cream', qty: 1/2, unit: 'cup' },
      { name: 'tomato puree', qty: 1, unit: 'cup' },
      { name: 'garam masala', qty: 1, unit: 'tsp' },
      { name: 'ginger-garlic paste', qty: 1, unit: 'tbsp' },
      { name: 'cilantro', qty: 2, unit: 'tbsp' },
    ]),
    steps: JSON.stringify([
      'Boil and mash potatoes and carrots, mix with crumbled paneer.',
      'Shape into balls and shallow fry until golden, set aside.',
      'Blend cashews with 1/4 cup water to make a paste.',
      'Heat oil in a pan and sauté onions until golden brown.',
      'Add ginger-garlic paste and cook for 1 minute.',
      'Add tomato puree and cook until oil separates.',
      'Add cashew paste, garam masala, and 1 cup water, simmer for 10 minutes.',
      'Add cream and cooked koftas, simmer for 5 minutes.',
      'Garnish with fresh cilantro and serve hot.',
    ]),
    cuisine: 'Indian',
    tags: JSON.stringify(['vegetarian', 'curry', 'comfort food', 'special occasion']),
    cookTime: 40,
    prepTime: 30,
    totalTime: 70,
    servings: 4,
    difficulty: 'medium',
    nutrition: JSON.stringify({ calories: 380, protein: 15, carbs: 25, fat: 25 }),
    mainIngredients: JSON.stringify(['potatoes', 'paneer', 'cashews']),
  },
  {
    title: 'Hyderabadi Biryani',
    description: 'Fragrant rice dish with tender meat and traditional Hyderabadi spices.',
    ingredients: JSON.stringify([
      { name: 'basmati rice', qty: 2, unit: 'cups' },
      { name: 'mutton', qty: 1, unit: 'lb' },
      { name: 'yogurt', qty: 1/2, unit: 'cup' },
      { name: 'onion', qty: 3, unit: 'large' },
      { name: 'tomatoes', qty: 3, unit: 'medium' },
      { name: 'ginger-garlic paste', qty: 1, unit: 'tbsp' },
      { name: 'biryani masala', qty: 2, unit: 'tbsp' },
      { name: 'saffron', qty: 1/2, unit: 'tsp' },
      { name: 'mint leaves', qty: 1/4, unit: 'cup' },
      { name: 'cilantro', qty: 1/4, unit: 'cup' },
    ]),
    steps: JSON.stringify([
      'Marinate mutton with yogurt and half the spices for 2 hours.',
      'Soak saffron in warm milk for 10 minutes.',
      'Fry sliced onions until golden brown, set aside half for garnish.',
      'Cook marinated mutton with tomatoes until tender and gravy thickens.',
      'Parboil rice with whole spices until 80% cooked.',
      'Layer rice and mutton in a heavy-bottomed pot.',
      'Sprinkle fried onions, mint, and cilantro between layers.',
      'Cover and cook on low heat for 25 minutes (dum cooking).',
      'Mix in saffron milk and serve hot with raita.',
    ]),
    cuisine: 'Indian',
    tags: JSON.stringify(['mutton', 'rice', 'dinner', 'special occasion']),
    cookTime: 50,
    prepTime: 30,
    totalTime: 80,
    servings: 4,
    difficulty: 'hard',
    nutrition: JSON.stringify({ calories: 580, protein: 30, carbs: 65, fat: 20 }),
    mainIngredients: JSON.stringify(['mutton', 'basmati rice', 'biryani masala']),
  },
  {
    title: 'Rajma',
    description: 'Hearty kidney bean curry cooked with onions, tomatoes and aromatic spices.',
    ingredients: JSON.stringify([
      { name: 'kidney beans', qty: 1, unit: 'cup' },
      { name: 'onion', qty: 2, unit: 'large' },
      { name: 'tomatoes', qty: 3, unit: 'medium' },
      { name: 'ginger-garlic paste', qty: 1, unit: 'tbsp' },
      { name: 'cumin', qty: 1, unit: 'tsp' },
      { name: 'coriander powder', qty: 1, unit: 'tsp' },
      { name: 'garam masala', qty: 1/2, unit: 'tsp' },
      { name: 'red chili powder', qty: 1, unit: 'tsp' },
      { name: 'amchur', qty: 1/2, unit: 'tsp' },
      { name: 'cilantro', qty: 2, unit: 'tbsp' },
    ]),
    steps: JSON.stringify([
      'Soak kidney beans overnight and pressure cook until tender.',
      'Heat oil in a pan and add cumin seeds.',
      'Add chopped onions and cook until golden brown.',
      'Add ginger-garlic paste and cook for 1 minute.',
      'Add chopped tomatoes and cook until soft and pulpy.',
      'Add all spices and cook for 1 minute.',
      'Add cooked kidney beans and 1 cup water, simmer for 20 minutes.',
      'Add amchur and cook for 2 minutes.',
      'Garnish with fresh cilantro and serve with rice.',
    ]),
    cuisine: 'Indian',
    tags: JSON.stringify(['vegetarian', 'curry', 'comfort food', 'gluten-free']),
    cookTime: 35,
    prepTime: 15,
    totalTime: 50,
    servings: 4,
    difficulty: 'easy',
    nutrition: JSON.stringify({ calories: 260, protein: 14, carbs: 45, fat: 3 }),
    mainIngredients: JSON.stringify(['kidney beans', 'onion', 'tomatoes']),
  },
  {
    title: 'Pav Bhaji',
    description: 'Mumbai street food with spiced mashed vegetables served with buttered bread rolls.',
    ingredients: JSON.stringify([
      { name: 'mixed vegetables', qty: 4, unit: 'cups' },
      { name: 'onion', qty: 2, unit: 'large' },
      { name: 'tomatoes', qty: 4, unit: 'medium' },
      { name: 'butter', qty: 3, unit: 'tbsp' },
      { name: 'pav bhaji masala', qty: 2, unit: 'tbsp' },
      { name: 'ginger-garlic paste', qty: 1, unit: 'tbsp' },
      { name: 'green chilies', qty: 2, unit: 'pieces' },
      { name: 'pav buns', qty: 8, unit: 'pieces' },
      { name: 'cilantro', qty: 2, unit: 'tbsp' },
      { name: 'lemon', qty: 1, unit: 'piece' },
    ]),
    steps: JSON.stringify([
      'Boil mixed vegetables until tender, drain and mash coarsely.',
      'Heat butter in a pan and sauté onions until golden.',
      'Add ginger-garlic paste and green chilies, cook for 1 minute.',
      'Add chopped tomatoes and cook until soft and pulpy.',
      'Add pav bhaji masala and cook for 2 minutes.',
      'Add mashed vegetables and 1/2 cup water, simmer for 15 minutes.',
      'Butter the pav buns and toast lightly.',
      'Serve hot bhaji with buttered pavs, chopped onions, and lemon wedges.',
    ]),
    cuisine: 'Indian',
    tags: JSON.stringify(['vegetarian', 'street food', 'comfort food', 'mumbai']),
    cookTime: 30,
    prepTime: 20,
    totalTime: 50,
    servings: 4,
    difficulty: 'medium',
    nutrition: JSON.stringify({ calories: 320, protein: 10, carbs: 45, fat: 12 }),
    mainIngredients: JSON.stringify(['mixed vegetables', 'butter', 'pav bhaji masala']),
  },
  {
    title: 'Vindaloo',
    description: 'Spicy Goan curry with Portuguese influences, made with vinegar and chilies.',
    ingredients: JSON.stringify([
      { name: 'pork', qty: 1, unit: 'lb' },
      { name: 'onion', qty: 2, unit: 'large' },
      { name: 'garlic', qty: 6, unit: 'cloves' },
      { name: 'ginger', qty: 1, unit: 'inch' },
      { name: 'vinegar', qty: 1/4, unit: 'cup' },
      { name: 'red chilies', qty: 8, unit: 'pieces' },
      { name: 'cumin', qty: 1, unit: 'tsp' },
      { name: 'coriander powder', qty: 1, unit: 'tsp' },
      { name: 'turmeric', qty: 1/2, unit: 'tsp' },
      { name: 'coconut milk', qty: 1/2, unit: 'cup' },
      { name: 'oil', qty: 2, unit: 'tbsp' },
      { name: 'cilantro', qty: 2, unit: 'tbsp' },
    ]),
    steps: JSON.stringify([
      'Cut pork into pieces and marinate with vinegar and salt for 1 hour.',
      'Heat oil in a pan and sauté onions until golden brown.',
      'Add ginger-garlic paste and cook for 1 minute.',
      'Add ground red chilies and all spices, cook for 2 minutes.',
      'Add marinated pork and 1 cup water, simmer covered for 40 minutes.',
      'Add coconut milk and simmer for 10 minutes.',
      'Adjust consistency and serve hot with rice.',
    ]),
    cuisine: 'Indian',
    tags: JSON.stringify(['pork', 'curry', 'spicy', 'goan']),
    cookTime: 60,
    prepTime: 20,
    totalTime: 80,
    servings: 4,
    difficulty: 'medium',
    nutrition: JSON.stringify({ calories: 380, protein: 30, carbs: 10, fat: 25 }),
    mainIngredients: JSON.stringify(['pork', 'red chilies', 'vinegar']),
  },
  {
    title: 'Kheer',
    description: 'Traditional Indian rice pudding made with milk, sugar, and aromatic spices.',
    ingredients: JSON.stringify([
      { name: 'rice', qty: 1/2, unit: 'cup' },
      { name: 'milk', qty: 4, unit: 'cups' },
      { name: 'sugar', qty: 1/2, unit: 'cup' },
      { name: 'cardamom', qty: 4, unit: 'pods' },
      { name: 'saffron', qty: 1/4, unit: 'tsp' },
      { name: 'cashews', qty: 10, unit: 'pieces' },
      { name: 'raisins', qty: 2, unit: 'tbsp' },
      { name: 'butter', qty: 1, unit: 'tbsp' },
      { name: 'cilantro', qty: 2, unit: 'tbsp' }
    ]),
    steps: JSON.stringify([
      'Wash rice and soak for 30 minutes, then drain.',
      'Heat milk in a heavy-bottomed pan and bring to a boil.',
      'Add rice and cook on low heat for 30 minutes, stirring occasionally.',
      'Crush cardamom pods and add to the kheer.',
      'Add saffron soaked in 1 tbsp warm milk.',
      'Add sugar and cook for 10 minutes until thick.',
      'Fry cashews and raisins in butter until golden.',
      'Add fried nuts to kheer and mix well.',
      'Cool and refrigerate before serving.',
    ]),
    cuisine: 'Indian',
    tags: JSON.stringify(['dessert', 'sweet', 'vegetarian', 'festival']),
    cookTime: 45,
    prepTime: 15,
    totalTime: 60,
    servings: 4,
    difficulty: 'easy',
    nutrition: JSON.stringify({ calories: 280, protein: 6, carbs: 45, fat: 8 }),
    mainIngredients: JSON.stringify(['rice', 'milk', 'sugar']),
  },
  {
    title: 'Litti Chokha',
    description: 'Bihari specialty with baked wheat balls filled with spiced lentils, served with mashed vegetables.',
    ingredients: JSON.stringify([
      { name: 'whole wheat flour', qty: 2, unit: 'cups' },
      { name: 'sattu', qty: 1, unit: 'cup' },
      { name: 'onion', qty: 1, unit: 'large' },
      { name: 'ginger-garlic paste', qty: 1, unit: 'tsp' },
      { name: 'cumin', qty: 1, unit: 'tsp' },
      { name: 'coriander powder', qty: 1, unit: 'tsp' },
      { name: 'garam masala', qty: 1/2, unit: 'tsp' },
      { name: 'eggplant', qty: 1, unit: 'medium' },
      { name: 'tomatoes', qty: 2, unit: 'medium' },
      { name: 'potatoes', qty: 2, unit: 'medium' },
    ]),
    steps: JSON.stringify([
      'Make dough with wheat flour and water, set aside.',
      'Mix sattu with spices, onions, and ginger-garlic paste to make filling.',
      'Divide dough and filling into equal portions.',
      'Stuff dough with filling and shape into rounds.',
      'Bake in oven at 375°F for 20 minutes until golden.',
      'Roast eggplant, tomatoes, and potatoes directly on flame until charred.',
      'Peel and mash vegetables, season with salt and lemon juice.',
      'Serve hot littis with chokha and ghee.',
    ]),
    cuisine: 'Indian',
    tags: JSON.stringify(['vegetarian', 'baked', 'bihari', 'comfort food']),
    cookTime: 30,
    prepTime: 40,
    totalTime: 70,
    servings: 4,
    difficulty: 'medium',
    nutrition: JSON.stringify({ calories: 320, protein: 14, carbs: 50, fat: 8 }),
    mainIngredients: JSON.stringify(['whole wheat flour', 'sattu', 'eggplant']),
  },
  {
    title: 'Gulab Jamun',
    description: 'Deep-fried milk-solid balls soaked in sugar syrup, a popular Indian dessert.',
    ingredients: JSON.stringify([
      { name: 'khoya', qty: 1, unit: 'lb' },
      { name: 'all-purpose flour', qty: 2, unit: 'tbsp' },
      { name: 'baking soda', qty: 1/4, unit: 'tsp' },
      { name: 'milk', qty: 2, unit: 'tbsp' },
      { name: 'sugar', qty: 1, unit: 'cup' },
      { name: 'water', qty: 1/2, unit: 'cup' },
      { name: 'cardamom', qty: 4, unit: 'pods' },
      { name: 'rose water', qty: 1/2, unit: 'tsp' },
      { name: 'oil', qty: 2, unit: 'tbsp' },
      { name: 'silver leaf', qty: 1, unit: 'piece' }
    ]),
    steps: JSON.stringify([
      'Knead khoya with flour, baking soda, and milk to make a soft dough.',
      'Divide into small portions and shape into smooth balls.',
      'Heat oil to medium-low temperature and fry until golden brown.',
      'Drain on paper towels.',
      'For sugar syrup, dissolve sugar in water with crushed cardamom.',
      'Bring to a boil and add rose water.',
      'Add fried jamuns to hot syrup and soak for 30 minutes.',
      'Garnish with silver leaf and serve warm or cold.',
    ]),
    cuisine: 'Indian',
    tags: JSON.stringify(['dessert', 'sweet', 'vegetarian', 'festival']),
    cookTime: 25,
    prepTime: 30,
    totalTime: 55,
    servings: 12,
    difficulty: 'medium',
    nutrition: JSON.stringify({ calories: 180, protein: 4, carbs: 25, fat: 7 }),
    mainIngredients: JSON.stringify(['khoya', 'sugar', 'cardamom']),
  },
  {
    title: 'Prawn Curry',
    description: 'Spicy and tangy curry with fresh prawns cooked in coconut and spice gravy.',
    ingredients: JSON.stringify([
      { name: 'prawns', qty: 1, unit: 'lb' },
      { name: 'coconut', qty: 1, unit: 'cup' },
      { name: 'onion', qty: 1, unit: 'large' },
      { name: 'garlic', qty: 4, unit: 'cloves' },
      { name: 'ginger', qty: 1, unit: 'inch' },
      { name: 'tomatoes', qty: 2, unit: 'medium' },
      { name: 'kokum', qty: 4, unit: 'pieces' },
      { name: 'cumin', qty: 1, unit: 'tsp' },
      { name: 'coriander powder', qty: 1, unit: 'tsp' },
      { name: 'red chili powder', qty: 1, unit: 'tsp' },
    ]),
    steps: JSON.stringify([
      'Clean and devein prawns, set aside.',
      'Grind coconut with 1/4 cup water to make a paste.',
      'Heat oil in a pan and sauté onions until golden.',
      'Add ginger-garlic paste and cook for 1 minute.',
      'Add chopped tomatoes and cook until soft.',
      'Add all spices and coconut paste, cook for 2 minutes.',
      'Add 1/2 cup water and bring to a boil.',
      'Add prawns and kokum, simmer for 5 minutes.',
      'Serve hot with rice or roti.',
    ]),
    cuisine: 'Indian',
    tags: JSON.stringify(['seafood', 'curry', 'gluten-free', 'coastal']),
    cookTime: 25,
    prepTime: 15,
    totalTime: 40,
    servings: 4,
    difficulty: 'easy',
    nutrition: JSON.stringify({ calories: 220, protein: 20, carbs: 8, fat: 12 }),
    mainIngredients: JSON.stringify(['prawns', 'coconut', 'kokum']),
  }
];

async function main() {
  console.log('Seeding database with unique recipes...');

  // First, clear all existing recipes to avoid any future duplicates
  await prisma.recipe.deleteMany();

  // Then add our unique recipes
  for (const recipe of sampleRecipes) {
    await prisma.recipe.create({
      data: recipe,
    });
  }

  console.log('Seeded', sampleRecipes.length, 'unique recipes');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });